### ISSUE TITLE
Android PedometerAPI.setupTracking()  crash

### ISSUE THREAD

**Issue by mykhailo-melnyk** [kilohealth/rn-fitness-tracker#54]
When I try to do:
`const authorizationStatus = await PedometerAPI.setupTracking();`
my application crashing

what I see in logcat:
![Screenshot at Jun 25 13-19-13](https://user-images.githubusercontent.com/14886932/123410405-f7ea7000-d5b7-11eb-87d3-1b459ec6b666.png)

**Comment by lukebars** [comment]
I've tested it on my end and it works as expected. Are you sure that you've completed [following steps](https://github.com/doville/rn-fitness-tracker#android)? 

If not, you could always create a small reproduction repo.

Also, I would recommend using default export FitnessTrackerAPI, that has Apple health integration, which handles Apple Watch and other step tracking data.

**Comment by mykhailo-melnyk** [comment]
@lukebars is it possible that it is related to debug mode?

**Comment by alarm109** [comment]
Pedometer is dropped from this package.
