### ISSUE TITLE
[iOS]: Step counts are displayed in decimal value

### ISSUE THREAD

**Issue by KushalDesai1** [kilohealth/rn-fitness-tracker#58]
Sometimes, the steps are displayed in decimal value. Just in iOS
![steps_decimal](https://user-images.githubusercontent.com/33296548/130312879-e77a5d2b-0c69-4ce6-b354-e9cfd775e8fc.png)

**Comment by lukebars** [comment]
Since v2 release, we're not providing step tracking methods anymore, so the values that you receive are coming straight from the native side as is. In this case I'd recommend fixing this on frontend side 🙏
